-- MySQL Script generated by MySQL Workbench
-- Mon Jun 29 17:33:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema larahub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema larahub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `larahub` DEFAULT CHARACTER SET utf8 ;
USE `larahub` ;

-- -----------------------------------------------------
-- Table `larahub`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `larahub`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `larahub`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `larahub`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `date_created` VARCHAR(45) NULL,
  `date_last_modified` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_questions_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `larahub`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `larahub`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `larahub`.`answers` (
  `id` INT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `date_created` VARCHAR(45) NULL,
  `date_last_modified` VARCHAR(45) NULL,
  `questions_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `right_answer` VARCHAR(10) NULL DEFAULT 'false',
  PRIMARY KEY (`id`, `questions_id`, `users_id`),
  INDEX `fk_answers_questions1_idx` (`questions_id` ASC) VISIBLE,
  INDEX `fk_answers_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_questions1`
    FOREIGN KEY (`questions_id`)
    REFERENCES `larahub`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `larahub`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `larahub`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `larahub`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_comments_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `larahub`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `larahub`.`comments_on_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `larahub`.`comments_on_question` (
  `questions_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  PRIMARY KEY (`questions_id`, `comments_id`),
  INDEX `fk_questions_has_comments_comments1_idx` (`comments_id` ASC) VISIBLE,
  INDEX `fk_questions_has_comments_questions_idx` (`questions_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_has_comments_questions`
    FOREIGN KEY (`questions_id`)
    REFERENCES `larahub`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_has_comments_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `larahub`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `larahub`.`comments_on_aswer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `larahub`.`comments_on_aswer` (
  `answers_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  PRIMARY KEY (`answers_id`, `comments_id`),
  INDEX `fk_answers_has_comments_comments1_idx` (`comments_id` ASC) VISIBLE,
  INDEX `fk_answers_has_comments_answers1_idx` (`answers_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_has_comments_answers1`
    FOREIGN KEY (`answers_id`)
    REFERENCES `larahub`.`answers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_has_comments_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `larahub`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `larahub`.`vote_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `larahub`.`vote_answer` (
  `vote_answer_id` INT NOT NULL AUTO_INCREMENT,
  `answers_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `vote_type` VARCHAR(45) NULL COMMENT 'like/dislike',
  PRIMARY KEY (`vote_answer_id`, `answers_id`, `users_id`),
  INDEX `fk_answers_has_vote_answers1_idx` (`answers_id` ASC) VISIBLE,
  INDEX `fk_vote_answer_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_has_vote_answers1`
    FOREIGN KEY (`answers_id`)
    REFERENCES `larahub`.`answers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_answer_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `larahub`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `larahub`.`vote_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `larahub`.`vote_question` (
  `vote_question_id` INT NOT NULL AUTO_INCREMENT,
  `questions_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `vote_type` VARCHAR(45) NULL COMMENT 'like/dislike',
  PRIMARY KEY (`vote_question_id`, `questions_id`, `users_id`),
  INDEX `fk_questions_has_vote_questions1_idx` (`questions_id` ASC) VISIBLE,
  INDEX `fk_vote_question_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_has_vote_questions1`
    FOREIGN KEY (`questions_id`)
    REFERENCES `larahub`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_question_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `larahub`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
